### ISSUE TITLE
Translation error: Signup pgage - Should be using tú/informal case throughout 

### ISSUE THREAD

**Issue by Beck-bili** [bilingualgeneration/bili-app#158]
Make sure the spanish is consistently in tú/informal tense
<img width="1119" alt="Screenshot 2024-01-24 at 8 34 26 AM" src="https://github.com/bilingualgeneration/bili-app/assets/157525984/725110dd-8291-4850-aac8-6762e9d014f3">
<img width="1235" alt="Screenshot 2024-01-24 at 8 35 52 AM" src="https://github.com/bilingualgeneration/bili-app/assets/157525984/eb07ad55-f318-47fc-a9f8-f1976ca996b2">

**Comment by fernperezg97** [comment]
Fixed in `commit 89a3a68d6896ca3b5c4a77a2a616d5e5ea165ee1` in `fer-fix-assigned-github-issues` branch

**Comment by fernperezg97** [comment]
Also fixed the formal/informal translation error in Locize

**Comment by Beck-bili** [comment]
Reopening since it is still showing up with the inconsistency 
<img width="556" alt="Screenshot 2024-01-31 at 8 35 12 AM" src="https://github.com/bilingualgeneration/bili-app/assets/157525984/b9e109b3-48e8-441d-9930-698b4de0c9de">
