### ISSUE TITLE
Translation error: Ages options should be translated to Spanish

### ISSUE THREAD

**Issue by Beck-bili** [bilingualgeneration/bili-app#159]
In spanish mode, age options are not translated. 

<img width="1119" alt="Screenshot 2024-01-24 at 8 34 26 AM" src="https://github.com/bilingualgeneration/bili-app/assets/157525984/c3792020-3e77-4c81-8f03-db5236dfe560">

**Comment by jonathan-chin** [comment]
to balance out the workload, @amak-code can you handle the age options? I think you need to update the component itself.

@fernperezg97 can you make the other changes on locize?

once you both have done this, I can review and close the issue.

**Comment by jonathan-chin** [comment]
@Beck-bili is this a repeat of #158 ?

**Comment by fernperezg97** [comment]
@jonathan-chin I think this is a repeat, but I fixed it regardless in #158

**Comment by Beck-bili** [comment]
I am still seeing the ages not translated and the issue from [#158](url) with the su (formal) in Spanish mode in the setup pages. 
<img width="556" alt="Screenshot 2024-01-31 at 8 35 12 AM" src="https://github.com/bilingualgeneration/bili-app/assets/157525984/3e5a94ed-9e9c-4659-a99f-18dcf374d4e2">

**Comment by fernperezg97** [comment]
@Beck-bili please see comment in [now closed] issue #160 😊
