### ISSUE TITLE
Translation error: Settings page - Should be using tú/informal case throughout 

### ISSUE THREAD

**Issue by Beck-bili** [bilingualgeneration/bili-app#160]
Español inclusivo: 
Aprende (Conoce) qué es el español inclusivo.

Explore:
Explora características especiales - tú case throughout

<img width="1229" alt="Screenshot 2024-01-24 at 8 53 28 AM" src="https://github.com/bilingualgeneration/bili-app/assets/157525984/88a69d10-b8e0-4b77-9b2e-7af02de4d265">

**Comment by jonathan-chin** [comment]
@fernperezg97 can you fix this in locize and close this issue once you do?

**Comment by fernperezg97** [comment]
Fixed and saved in Locize!

**Comment by Beck-bili** [comment]
Still seeing this issue so I am reopening

<img width="679" alt="Screenshot 2024-01-31 at 8 31 33 AM" src="https://github.com/bilingualgeneration/bili-app/assets/157525984/6ba479dd-5868-434e-8e96-95c39321dbfa">

**Comment by fernperezg97** [comment]
@Beck-bili I fixed it in Locize (the platform that helps manage and update the language translations), but @jonathan-chin still has to manually load those changes to reflect on our UI. Here is a good way of looking at it I think:

Think of Locize like a library of UI elements, and Jon as the librarian who manages updates once a week. 👨‍🏫 😂 When changes are made by Sasha or I, they're like new books being added or edited. 📚 However, just as the librarian would need time to process and reshelve books, Jon needs time to implement and update the changes in the UI. So, there's a delay between making changes and seeing them reflected in the UI because it takes time for Jon to update everything during his weekly update session. 🎉 

LOL feel free to let me know if that did or did not help @Beck-bili!

I think Jon mentioned that the changes made during the week should reflect the following Monday, but @jonathan-chin correct me if I'm wrong!
