### ISSUE TITLE
Translation error: Tutorial - Should be using tú/informal case throughout 

### ISSUE THREAD

**Issue by Beck-bili** [bilingualgeneration/bili-app#161]
<img width="1556" alt="Screenshot 2024-01-24 at 8 37 55 AM" src="https://github.com/bilingualgeneration/bili-app/assets/157525984/2b2d9aad-2f32-4db8-be9f-7d746c4b230a">

**Comment by jonathan-chin** [comment]
@fernperezg97 can you fix this in locize and close this issue when you do?

**Comment by fernperezg97** [comment]
Fixed and saved in Locize!

**Comment by Beck-bili** [comment]
I just signed up in English mode and selected bilingual setting and this still shows up in su form. I haven't tested it in the other modes but thought I would reopen it so you can look into that setting. 
<img width="1256" alt="Screenshot 2024-01-31 at 8 27 13 AM" src="https://github.com/bilingualgeneration/bili-app/assets/157525984/aa0d2f34-d1c9-40fd-a3b3-366ab77cf8a3">
